### ISSUE TITLE
run error with ruby-2.0.0 mechanize-1.0.0

### ISSUE THREAD

**Issue by fz68** [seattlerb/omnifocus-redmine#8]
```
#of sync
/Library/Ruby/Gems/2.0.0/gems/rb-appscript-0.6.1/lib/_appscript/terminology.rb:57: warning: assigned but unused variable - rev
scanning redmine
/Library/Ruby/Gems/2.0.0/gems/mechanize-1.0.0/lib/mechanize.rb:442: warning: assigned but unused variable - chain
/Library/Ruby/Gems/2.0.0/gems/mechanize-1.0.0/lib/mechanize.rb:564: warning: assigned but unused variable - response_body
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb:101: warning: assigned but unused variable - id
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- iconv (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-1.0.0/lib/mechanize.rb:11:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/lib/omnifocus.rb:149:in `mechanize'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-redmine-1.2.5/lib/omnifocus/redmine.rb:40:in `populate_redmine_tasks'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/lib/omnifocus.rb:226:in `block in cmd_sync'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/lib/omnifocus.rb:223:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/lib/omnifocus.rb:223:in `cmd_sync'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/lib/omnifocus.rb:251:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/omnifocus-2.1.3/bin/of:17:in `<top (required)>'
    from /usr/bin/of:23:in `load'
    from /usr/bin/of:23:in `<main>'
```

**Comment by fz68** [comment]
OK after `gem install iconv`
